disabled_rules:
  - function_parameter_count
  - trailing_whitespace
  - nesting
opt_in_rules:
  - empty_count
  - force_unwrapping
  - private_outlet
line_length:
  warning: 250
  error: 300
  ignores_function_declarations: false
  ignores_comments: true
type_body_length:
  warning: 300
  error: 400
identifier_name:
  allowed_symbols:
    - _
  excluded:
    - id
    - URL
cyclomatic_complexity:
  warning: 12
type_name:
    min_length: 2
    max_length: 40
included:
  - HiringApp/
excluded:
  - HiringApp/Resources/Localizables
  - Pods/
