# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HiringApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HiringApp
  pod 'BNRDeferred'
  pod 'HiringAppCore', :path => 'HiringAppCore'

  target 'HiringAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HiringAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
