# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HiringApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HiringApp
  pod 'HiringAppCore', :path => 'HiringAppCore'

  target 'HiringAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Decodable'
  end

  target 'HiringAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'BNRDeferred'
                config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = "$(inherited) DEBUG"
            end
        end
    end
end

end
